# permissions for end users to view podspecworkloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podspecworkload-viewer-role
rules:
- apiGroups:
  - standard.oam.dev
  resources:
  - podspecworkloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - standard.oam.dev
  resources:
  - podspecworkloads/status
  verbs:
  - get
